@BASE = http://localhost:3000
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21lIjoiVXN1w6FyaW8gbm92byIsImVtYWlsIjoibm92b0BpZnJzLmVkdS5iciIsInBlcmZpbCI6ImNsaWVudGUiLCJpYXQiOjE3ODc4NDAyMTksImV4cCI6MTc4Nzg0MzgxOX0.LGdHwuZMTeDW0HTZWiz-KMkUQ8ha0TSJgOeYjhIAlkQ

### Rota pública (acesso livre)
GET {{BASE}}/public/home
Content-Type: application/json

### Cadastro de novo usuário
POST {{BASE}}/auth/register
Content-Type: application/json

{
    "nomeUsuario": "Usuário novo",
    "emailUsuario": "novo@ifrs.edu.br",
    "senha_hash": "senha123",
    "perfil": "cliente"
}

### Login do novo usuário (pegar o token gerado abaixo)
POST {{BASE}}/auth/login
Content-Type: application/json

{
    "emailUsuario": "novo@ifrs.edu.br",
    "senha_hash": "senha123"
}

### Login do usuário comum (usuário já existente no banco)
POST {{BASE}}/auth/login
Content-Type: application/json

{
    "emailUsuario": "novo@ifrs.edu.br",
    "senha_hash": "senha123"
}

### Login do administrador (usuário já existente no banco)
POST {{BASE}}/auth/login
Content-Type: application/json

{
    "emailUsuario": "admin@probeauty.com",
    "senha_hash": "senha123"
}

### Acesso ao painel (rota protegida, requer token de qualquer usuário autenticado)
GET {{BASE}}/protected/dashboard
Authorization: Bearer {{TOKEN}}

### Acesso à área admin (rota protegida, requer token de usuário com perfil "admin")
GET {{BASE}}/protected/admin
Authorization: Bearer {{TOKEN}}