@BASEURL = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21lIjoiVXN1w6FyaW8gbm92byIsImVtYWlsIjoibm92b0BpZnJzLmVkdS5iciIsInBlcmZpbCI6ImNsaWVudGUiLCJpYXQiOjE3ODc4NDAyMTksImV4cCI6MTc4Nzg0MzgxOX0.LGdHwuZMTeDW0HTZWiz-KMkUQ8ha0TSJgOeYjhIAlkQ

### Rota pública (acesso livre)
GET {{BASEURL}}/public/home
Content-Type: application/json

### Cadastro de novo usuário
POST {{BASEURL}}/auth/register
Content-Type: application/json

{
    "nomeUsuario": "Usuário novo",
    "emailUsuario": "novo@ifrs.edu.br",
    "senha_hash": "senha123",
    "perfil": "cliente"
}

### Login do novo usuário (pegar o token gerado abaixo)
POST {{BASEURL}}/auth/login
Content-Type: application/json

{
    "emailUsuario": "novo@ifrs.edu.br",
    "senha_hash": "senha123"
}

### Login do usuário comum (usuário já existente no banco)
POST {{BASEURL}}/auth/login
Content-Type: application/json

{
    "emailUsuario": "novo@ifrs.edu.br",
    "senha_hash": "senha123"
}

### Login do administrador (usuário já existente no banco)
POST {{BASEURL}}/auth/login
Content-Type: application/json

{
    "emailUsuario": "admin@probeauty.com",
    "senha_hash": "senha123"
}

### Acesso ao painel (rota protegida, requer token de qualquer usuário autenticado)
GET {{BASEURL}}/protected/dashboard
Authorization: Bearer {{token}}

### Acesso à área admin (rota protegida, requer token de usuário com perfil "admin")
GET {{BASEURL}}/protected/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5AcHJvYmVhdXR5LmNvbSIsInBlcmZpbCI6ImFkbWluIiwiaWF0IjoxNzg3ODQwMjQ4LCJleHAiOjE3ODc4NDM4NDh9.HvJNpKR7uuDNze_tjbNf79ZDltH0gCFUOxWlla4u42k