@BASE = http://localhost:3000
@TOKEN = 

### Login do novo usuário (pegar o token gerado abaixo)
POST {{BASE}}/auth/login
Content-Type: application/json

{
    "emailUsuario": "admin@probeauty.com",
    "senha_hash": "senha123"
}

### Listar todos os profissionais
GET {{BASE}}/profissionais
Accept: application/json
Authorization: Bearer {{TOKEN}}

### Criar um novo profissional
POST {{BASE}}/profissionais
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "nomeProfissional": "Maria Silva",
    "especialidade": "Manicure",
    "telefone": "54 98888-6666",
    "ativo": "1"
}

### Atualizar um profissional existente
PUT {{BASE}}/profissionais/1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "nomeProfissional": "Maria Silva",
    "especialidade": "Maquiadora",
    "telefone": "54 99999-8888",
    "ativo": "1"
}

### Atualizar um profissional inexistente
PUT {{BASE}}/profissionais/999
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "nomeProfissional": "Profissional Inexistente",
    "especialidade": "Maquiadora",
    "telefone": "54 99999-8888",
    "ativo": "1"
}

### Deletar um profissional
DELETE {{BASE}}/profissionais/1
Accept: application/json
Authorization: Bearer {{TOKEN}}

### Deletar um profissional inexistente
DELETE {{BASE}}/profissionais/999
Accept: application/json
Authorization: Bearer {{TOKEN}}